---

# This file was automatically generated by Aegir <?php print $this->version; ?>

# on <?php print date('r'); ?>.

parameters:
  session.storage.options:
    cookie_domain: '<?php print $this->cookie_domain; ?>'
